### ISSUE TITLE
Flytte task analytics til dekoratør fra GTM

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/nav-dekoratoren_legacy#1001]
Flytt task analytics script fra GTM til dekoratøren

Hver task analytics undersøkelse lastes inn via en javascript fil med unik URL.

Ideelt sett så bør all tredjepartskode for sporing og måling ligge i applikasjoner som dekoratøren slik at utviklere kan tilpasse de og slå de av og på etter behov.

**Comment by ojnybo** [comment]
Vurdere å flytte all måling ut av GTM

**Comment by terjeofnorway** [comment]
Løsning i denne omgang:
- Teamene kan oppgi en array av koder (hver survey har en individuell identifiserbar kode).
- Utover det må teamene selv sette opp surveyen i TA, feks trigger URL, invitasjonsrate osv.
- Team som ikke vil ha noen survey kan hele propertyen eller sende inn tom array.

Todo:
- Kikke på hvordan teamene kan endre oppgitte surveykoder inn til Dekoratøren uten å måtte redeploye appen sin.
