### ISSUE TITLE
Redusere lastemengde fra endepunktet

### ISSUE THREAD

**Issue by Havardmj** [navikt/nav-dekoratoren_legacy#1016]
Dekoratøren har falt en del på responstid via testing av applikasjonen mot Lighthouse. Her finner vi at Psplugin som er skjermdeling scriptet utgjør 40% av opprinnelig mengden. Dette scriptet trenger ikke lastes ned første lasting av applikasjonen, men kan heller settes som en dynamisk loading når en trykker på skjermdelingslenken. Dette vil forbedre resultatet til responsen.

**Comment by ojnybo** [comment]
Erstattes av https://github.com/navikt/nav-dekoratoren/issues/1019
