### ISSUE TITLE
UU: ... knapp i brødsmulestien ikke compliant

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-dekoratoren_legacy#1017]
Avvik mellom aria-label (Vis hele brødsmulestien) og visning (...).
Eksempelside:
https://www.nav.no/no/nav-og-samfunn/kontakt-nav/utbetalinger/skattetrekk-pa-ytelser-fra-nav/arsoppgave-fra-nav
Mulig løsning:
Bytte ut ... med et ikon/image

**Comment by ojnybo** [comment]
Lukker denne, brødsmulestiene skal fjernes på sikt og problemet blir mindre og mindre
