### ISSUE TITLE
Tilgjenglighetserklæring i footer

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#1021]
Tilgjenglighetserklæring i footer via en lenke som åpner en modall med 2 lenker videre til DIFI sin uu erklæringsskjema.

Vi skal få tilsendt skjermbilder fra uu team, for å få en tett tilknyttning til erklæringsskjema vi skal linke til.

**Comment by ojnybo** [comment]
Fra @Lillebo: 

> Vi ser for oss at vi lager en overordnet erklæring for nav.no generelt, og så kan individuelle team lage egne erklæringer for områder/apper på nav.no som de "eier". Vi er litt usikker på hvem som skal/bør "eie" den overordnede erklæringen - kanskje vi i UU-teamet, kanskje dere, eller kanskje kommunikasjon?
> 
> Løsningen vi foreslår vil uansett kreve litt arbeid fra dere med å utvide dekoratøren (footeren) med litt funksjonalitet. Først denne lenken som åpner modalen med informasjon, og så en ekstra optional prop hvor konsumentene kan mate inn en URL til erklæringen for sitt team.
> 
> Som sagt så har vi litt god tid på oss enda, da dette strengt tatt ikke må være på plass før 2023. Samtidig tror jeg Digdir tar sikte på å lansere sin fellesløsning ganske tidlig i 2022, og da tenker jeg det bare hadde vært fint om vi var klare til å bruke den jo før, jo heller.
> 
> Se også her for litt mer informasjon: https://www.uutilsynet.no/webdirektivet-wad/tilgjengelegheitserklaering/267

**Comment by ojnybo** [comment]
Lukker denne og fortsetter saken i https://github.com/navikt/nav-dekoratoren/issues/1110
