### ISSUE TITLE
Se på plassering av "Del skjerm med veileder" i footer

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren_legacy#1037]
Tilbakemelding fra NKS:
![image](https://user-images.githubusercontent.com/47320658/140734240-eb55f85b-6da5-4eab-ae9a-afa8163862ba.png)

Fremmedspråklige sliter med å finne navigere til "Del skjerm med veileder" i footer. Vi må se på hvordan vi kan gjøre det enklere for denne brukergruppen å finne knappen.

**Comment by macbruker** [comment]
Jeg har et forslag som gjerne kan brukes som grunnlag for videre diskusjon av løsning.

Stor skjerm
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1032194/198968070-5c53747b-12b3-45c4-aec2-4ab4d22bd660.png">

Liten skjerm
![image](https://user-images.githubusercontent.com/1032194/198968342-28182755-9100-4066-9ffc-e258a2614648.png)

**Comment by macbruker** [comment]
Undersøke om det er et faktisk problem. Hvis det er tilfelle kan vi se på mulighet for å legge inn hurtigtast eller noe lignende.

**Comment by anders-nom** [comment]
Endres i decorator-next
