### ISSUE TITLE
Eksponere som react komponent.

### ISSUE THREAD

**Issue by hakonph** [navikt/nav-dekoratoren_legacy#1040]
Hadde vert fint og bare kunne bruke dene som en react komponent.

**Comment by anders-nom** [comment]
Denne ble visst liggende en stund, sorry! 😄 

Det er noen utfordringer ved å implementere denne som en react-komponent. Dekoratøren hentes i dag ut fra nav.no/dekoratoren, der vi kontinuerlig deployer siste versjon. Dette for å holde dekoratøren i sync på tvers av alle appene på nav.no. Dersom vi f.eks. hadde distribuert den som en versjonert NPM-pakke med react-komponenter, så ville vi vært avhengig av at alle holdt denne pakka oppdatert i appene sine for å unngå fragmentering på tvers av nettstedet.

Et mulig alternativ (som kanskje var det du tenkte på) kunne vært å ha react-komponenter som fetcher dekoratør-elementene, men dette vil ikke fungere med server-side rendering. Client-side rendering av dekoratøren gir en ganske kjip brukeropplevelse med layout-shifting når headeren rendres, det er noe vi ikke vil oppfordre til. Server-components kan kanskje være en mulighet på sikt, når dette er en mer stabil feature i react.

Lukker denne for nå, vi har det på blokka å utforske alternative måter å implementere dekoratøren på i tiden fremover. Se også https://github.com/navikt/decorator-next/issues/207
