### ISSUE TITLE
Spore bruk av hopplenker i header

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/nav-dekoratoren_legacy#1061]
Ref spørsmål på slack så lurer vi på hvor mange som bruker hopplenker i header som f.eks

* hovedmeny
* søk 
* hovedinnhold

https://nav-it.slack.com/archives/C7NE7A8UF/p1641288482144500?thread_ts=1640159982.116800&cid=C7NE7A8UF

**Comment by ojnybo** [comment]
Duplikat av https://github.com/navikt/nav-dekoratoren/issues/1056
