### ISSUE TITLE
Erstatte placeholder med label i søkefelt

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren_legacy#1096]
Innspill fra #søk-på-navno på Slack
![image](https://user-images.githubusercontent.com/47320658/157855634-686e50eb-d9f3-485c-aeb5-3c2bc8360fb6.png)

**Comment by ojnybo** [comment]
Bruk gjerne søkefeltet til gov.uk som inspirasjon

**Comment by eivindskifjeld** [comment]
Møte mellom Terje, Chris og meg torsdag 07.04. Chris viste noen skisser, men vi tar opp igjen tråden etter påske når Chris har fått snakket med UU-teamet.
