### ISSUE TITLE
Alertstripe i dekoratøren - funksjon og design

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1140]
Justere varsel på forsiden og artikkel sider. 
Utforming og plassering.

Global og lokal varsel.

https://www.figma.com/file/GrS0ISeUwSL2373F5pmNfl/%E2%AD%90%EF%B8%8FSandkasse?node-id=2859%3A37330

- [ ] fjerne mulighet for info-ikon?
- [ ] animasjon?

**Comment by ojnybo** [comment]
@chrisarnesen hva er status på denne?

**Comment by ojnybo** [comment]
Fikset opp UU-messig. Ses på i sammenheng med språkvelger / maler 2.0
Gamle figma-filer, må se på design på nytt.

**Comment by anders-nom** [comment]
Ikke relevant lengre
