### ISSUE TITLE
Fjerne utloggingsvarsel fra dekoratør

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-dekoratoren_legacy#1236]
Ref diskusjon på Slack, så fjerner vi utloggingsvarsel i dekoratøren. Den fungerer ikke som tenkt og må uansett skrives om. Da er det bedre å begynne fra scratch siden koden er litt for kompisert.

- [x] Fjerne selve koden
- [x] Fjerne dokumentasjon
- [x] [Fjern fra dekoratoren-moduler](https://github.com/navikt/nav-dekoratoren-moduler/pull/47)
- [x] Varsle før vi fjerner? https://github.com/search?q=org%3Anavikt+%22utloggingsvarsel%3A+true%22&type=code
- [x] Fjerne bruk i personopplysninger-app

**Comment by androa** [comment]
Denne kommer tilbake når https://github.com/navikt/nav-dekoratoren/issues/573 er løst (i løpet av sommeren har noen sagt ❤️)
