### ISSUE TITLE
VoiceOver: "Hva kan vi hjelpe deg med"-bug

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren_legacy#1245]
![image](https://user-images.githubusercontent.com/47320658/185880315-e1eb366f-18a2-4fbc-87f6-791507b13aa1.png)

Se slack: https://nav-it.slack.com/archives/CAFRFDJMN/p1661153133464349

**Comment by terjeofnorway** [comment]
Jeg har kikket endel på dette. Forsøk på problembeskrivelse:

- Kan kun gjenskapes ved sveip-navigasjon i accessibility mode i iOS (Safari og Chrome).
- Sveip lett i toppen av skjermen for å "tastaturnavigere" mellom klikkbare elementer
- Sveip ned til "Snarveier" og dobbeltapp skjermen (fordi du er i accessibility mode)

Nå står man fast hvis man forsøker å sveipe på nytt for å navigere og må istedet klikke på ett av menypunktene. Dette fungerer som det skal og brukeren blir forsåvidt ikke stående helt fast om vedkommende klikker vilkårlig på skjermen.

Det kan se ut til at dette er en miks av hvordan vi har kodet menyen i dekoratøren og at voiceover (iOS) ikke alltid henger helt med i svingene. Dette er feks ikke et problem ved vanlig tastaturnavigasjon på MacOS eller Windows.

Eksempel:
- Dersom jeg feks fjerner hele DOM-treet via inspector så står voiceover fortsatt fast på et ikke-eksisterende element. Det kan tyde på at voiceover sliter med å oppdatere focus ettersom DOM endrer seg.

Jeg foreslår at vi konkluderer dette som en "won't fix", siden det vil kreve en større omskriving av menystrukturen i dekoratøren
