### ISSUE TITLE
Bytt ut ikoner i headeren med SVGer (før og etter animasjon)

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1253]
Ved zoom f.eks. 110 ser ikonene ikke helt bra ut nå, fordi de er laget med html og css for å støtte animasjon. Kan være mulig å vise svg når de er statiske og bytte den ut med html og css bare under selve animasjonen.

![image](https://user-images.githubusercontent.com/71373910/188434590-4e62c3c6-9e62-4486-b034-c2413da5035a.png)

**Comment by macbruker** [comment]
Det går fint å animere SVG-elementene med CSS også. Jeg har satt opp en demo 🤓 
https://delicate-sunburst-edd62f.netlify.app/animasjon/
