### ISSUE TITLE
Fjern to av tre skiplinks

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1280]
### Svar fra Sarah Brodwall 23.11:
"Oki!  Vi foreslår at dere beholder "Hopp til hovedinnholdet" og ditcher resten.  Jeg skriver en [Aksel-artikkel]"(https://aksel.nav.no/god-praksis/artikler/skip-links?tema=universell-utforming) om at dette er rådet og hvorfor.

### Hovedpunktene til Morten, til vurdering:
- [x] "Som mange vet synes jeg personlig skip-lenkene på nav kan fjernes, ingen bruker de, men noen har vel lært at sånn skal det være."
![Screenshot 2022-11-10 at 12 23 21](https://user-images.githubusercontent.com/71373910/201078697-75f40428-85bb-4796-87e7-2b783a53d517.png)
![image](https://user-images.githubusercontent.com/71373910/201079606-2bcd0535-9e2b-44fc-ab47-05cccc6ce418.png)
https://webaim.org/techniques/skipnav/#other

- [x] "Altså er det som kalles "Hovedmeny" en nav som inneholder en nav (velg brukergruppe), Søk, Meny og Logg inn. Hovedmeny brukes med andre ord ulikt når det presenteres for skjermleser og det som er tenkt med skip-lenken "Hopp til hovedmeny". Ikke helt perfekt, eller?"
- [x] "Nav-tag'en for brukergruppe er strengt talt også veldig overflødig og fører kun til en ting "ekstra støy for skjermleser". En nav-tag (hovedmeny) som inneholder såpass lite bør ikke inneholde andre nav-tag'er synes jeg."

### Bakgrunn

[Tråd oktober](https://nav-it.slack.com/archives/CAFRFDJMN/p1665564695419999)

[Tråd januar](https://nav-it.slack.com/archives/CAFRFDJMN/p1641370453041000)

[Tråd desember 2021](https://nav-it.slack.com/archives/C7NE7A8UF/p1640159982116800)

[Hvor mange bruker skiplinks (Amplitude)](https://analytics.eu.amplitude.com/nav/chart/e-5uvfjv3/edit/e-tf4j5v9)

[WCAG 2.4.1 Bypass Blocks](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-skip.html)

- [x] Gi Morten en tilbakemelding på status

[teamdiskusjon](https://nav-it.slack.com/archives/GNP7GJU6M/p1668088077690789)

**Comment by ojnybo** [comment]
Utviklerne tar en diskusjon om denne på utviklermøte torsdag
