### ISSUE TITLE
(kanskje) scope gammel designsystem-styling til kun chatbotten

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1283]
Prefixe css-en med noe annet enn decorator-wrapper?

Finn ut om det er noe av stylingen som fortsatt påvirker noe utenfor chatbotten.

Selv om det ikke gjør det nå, så kan det kanskje være lurt å scope stylingen så det heller ikke skjer med nye ting vi lager.

**Comment by anders-nom** [comment]
Ny chat-klient er rett rundt hjørnet, denne har sin egen CSS-løsning og bruker ikke komponenter fra dekoratøren lengre.
