### ISSUE TITLE
Eksterne scripts krasjer footeren ved enkelte nettleser-innstillinger

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#1286]
Bruk av localStorage/sessionStorage uten error catching ser ut til å være årsaken

**Comment by ojnybo** [comment]
Vergic og Task-Analytics

**Comment by ojnybo** [comment]
OJ melder inn til Vergic, Tobias melder inn til TA

**Comment by tobiasmcvey** [comment]
Jeg har testet og det ser ikke ut som det er et problem med Task analytics. @anders-nom ser det samme. Ser ut som de har feilhåndtering for dette i Task analytics.

**Comment by ojnybo** [comment]
Siste oppdatering fra @anders-nom : Problemet er/var at sessionStorage.setItem() kaster en error i private mode på Safari, som ps.js scriptet ikke håndterer. Det ser ut som problemet er løst i nyere versjoner av Safari, jeg klarte ikke å gjenskape det på noen måte nå.

Den kan oppstå på gamle enheter, spesielt eldre iOS-enheter som ikke får oppdateringer lengre. Men det gjelder nok veldig få brukere, vi har hatt totalt 24 slike feil de siste 2 mnd'ene ser jeg i sentry.

Lukker saken
