### ISSUE TITLE
Sett lang-attribute på header og footer som matcher faktisk språk som vises

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#1326]
Header og footer containere bør ha en lang-attribute som tilsvarer det språket de faktisk vises på.

Dekoratøren godtar språkene nb, nn, en, se (samisk), pl, uk og ru.
Derimot finnes det kun oversettelser for nb, en og se.

I tillegg til å sette lang-attributt på header og footer, trengs også en form for languageMapper slik at feks lang="nb" settes i header og footer dersom man har sendt inn se som ```language```.

**Comment by terjeofnorway** [comment]
Samisk versjon av dekoratøren er litt halvveis oversatt. Foreslår at vi blir enige om hvorvidt ihvertfall header skal være fullt ut oversatt før vi gjør noe mer på denne oppgaven.

![dekorator-samisk](https://user-images.githubusercontent.com/1443997/211538145-7ceb2e32-16e9-45f8-8591-b07387f8a075.png)
