### ISSUE TITLE
Legg til målgruppe fra metadata i enonic når vi logger besøk i Amplitude

### ISSUE THREAD

**Issue by tobiasmcvey** [navikt/nav-dekoratoren_legacy#1331]
Vi ønsker å kunne aggregere og filtrere på innholdet for personbruker

Vi kan nok gruppere innholdet som enten ligger i gammel ingress under www.nav.no/no/person, og det som ligger i nye maler og har målgruppe

**Comment by PerOlavM** [comment]
Kan bruke parametere.CONTEXT til å filterer på sider som har satt kontekst i dekoratøren.
Forslaget er å utvide dekoratøren til å kunne ta i mot flere parametere knyttet til event besøk, men dette er en litt større oppgave. Lager en oppgave i backloggen til Dekoratøren.
