### ISSUE TITLE
Feil med aria-label "Velg brukergruppe"

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1333]
axe DevTools sier:

aria-label attribute is not well supported on a div with no valid role attribute.

Det som før var en nav er nå en div

Skjedde i sammenheng med fjerning av 2/3 skiplinks

**Comment by bdahle** [comment]
Må se litt nøyere på hva som er hensiktsmessig med bruk av nav og aria-labels i toppnavigasjon

**Comment by PerOlavM** [comment]
Løsningsforslag: 
Vi fjerner div og innfører role="menubar" for ul. 
ul får aria-label.
https://www.w3.org/WAI/ARIA/apg/patterns/menu/
Vurder:
Legge på role = menu og role = menuitem i menyen også
