### ISSUE TITLE
Feil farge ved lang brødsmulesti

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1335]
![image](https://user-images.githubusercontent.com/71373910/208858351-0c12bc7f-02a7-4ab8-9375-447b9336ce5a.png)

Eksempel:
www.nav.no/no/lokalt/oslo/nav-arbeidslivssenter-oslo/nyheter-oslo/opplaeringsvideoer/visste-du-dette-partssamarbeid

**Comment by eivindskifjeld** [comment]
Testet 27. januar 2023 i dev. Ok.
