### ISSUE TITLE
Task Analytics: Styre aktive TA-koder og segmentering via ConfigMap

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-dekoratoren_legacy#1347]
- Bør kunne slå av og på én og flere TA-koder via Content Studio slik at vi slipper å deploye ut ny release hver gang.
- Bør også kunne angi hvilke sider eller grupper av sider (via sti / url) som en bestemt TA-kode skal trigge på.

**Comment by tobiasmcvey** [comment]
* Bør også kunne angi hvilke sider eller grupper som en bestemt undersøkelse **ikke** skal trigge på

**Comment by ojnybo** [comment]
Duplikat av https://github.com/navikt/nav-dekoratoren/issues/1027. Lukker den andre og beholder denne: 

Dette ligger også i den andre oppgaven:

I dag feedes TA-kode inn i Dekoratøren pr app som en parameter. Det gjør at vi ikke enkelt kan krysspublisere undersøkelser på tvers av apper uten at teamene selv legger de inn som en parameter der Dekoratøren hentes inn.

Behov:

1. Vi trenger et felles sted å legge inn TA-koder slik at disse hentes av Dekoratøren uavhengig av hvilken app som Dekoratøren vises igjennom.
2. Vi må kunne filtrere oppstart av undersøkelser avhengig av URL (regex?) slik at den aktuelle undersøkelsen kun starter opp på de aktuelle URL'ene. Dette gjelder da også teamenes egne apper.
3. Man må kunne ha flere undersøkelser gående samtidig, enten parallelt på samme URL'er eller fordi man har individuelle undersøkelser pr app.
4. Team må i tillegg kunne legge inn sine egne TA-koder som et parameter i Dekoratøren (slik funksjonen er i dag) dersom de ønsker det.
