### ISSUE TITLE
Bytt til semantiske farger

### ISSUE THREAD

**Issue by bdahle** [navikt/nav-dekoratoren_legacy#1374]
https://github.com/navikt/nav-dekoratoren/pull/1362#issuecomment-1408576659

**Comment by macbruker** [comment]
Jeg begynte på denne oppgaven, men konkluderte etterhvert med at det har lav verdi å gjøre endringene nå. Dette er en kodebase "alle" ønsker å skrive på nytt, og jeg tror det er et bedre tidspunkt å introdusere ryddig bruk av variabler. 

Nå er koden er en blanding av hardkodede farger, Sass-variabler og custom properties fra designsystemet. Noen steder er det forskjell mellom fargen vi bruker, og "riktig" semantisk farge fra DS. Enkelte steder er det også uklart hvilke semantisk fargenavn som er riktig å bruke.

**Comment by macbruker** [comment]
Revurderte denne og har gjort et solid forsøk på å rydde og fikse.

**Comment by terjeofnorway** [comment]
@macbruker Skal vi kanskje lukke denne hvis det er slik at vi har fått gjort så mye vi kan? (Ref diskusjonen før sommeren om at ikke alle fargeverdier kan mappes om til semantiske farger på en meningsfull måte.)

**Comment by macbruker** [comment]
Ja, det er ikke nødvendig å bruke krefter på denne nå.
