### ISSUE TITLE
Vise målgruppe i søkeresultater

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#1384]
Sette opp noe tilsvarende som på nav.no/sok. Benytt gjerne anledningen til å gjøre utlistingen av søkeresultater generelt litt penere også 😄

**Comment by bdahle** [comment]
- [ ] sjekk at logging til amplitude virker som før
- [x] sjekk om keyboard-nav funker (piler)
- [ ] sjekk visning mindre skjermer, legg til skygge som på nav.no/sok?

**Comment by bdahle** [comment]
avventer: "vi lar all arbeid med søk ligge. Bjørnar jobber med ny backend og vi har en del tanker og ønsker på forbedringsmuligheter av søk. Så vi skal avsette tid til søk i Q4 eller Q1/2."

**Comment by anders-nom** [comment]
Må løses på en annen måte med det nye søket
