### ISSUE TITLE
Skiplink vises ikke alltid ved client-side rendering av maincontent

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#1387]
Dersom #maincontent-elementet til appene rendres etter at dekoratøren har gjort sin sjekk på om #maincontent finnes, så vil ikke skiplinken vises.

Løses i de enkelte appene (maincontent flyttes til page template):

- [ ] navno-frontend (NextJS)
- [x] Samisk samtale - Per Olav
- [x] Tilbakemeldinger - Per Olav
- [x] Personopplysninger - Per Olav
- [ ] Søkefrontend (NextJS)
- [x] Kontorsøket - Per Olav

**Comment by ojnybo** [comment]
Mulig det kan løses i den nye dekoratøren?

**Comment by PerOlavM** [comment]
Har foreløig ikke funnet noen god metode for å løses dette i Next-appene våre.

**Comment by anders-nom** [comment]
Ingen av next-appene våre bruker client-side rendering, så det burde gå fint.

Dette burde forøvrig løses generelt i dekoratøren, slik at den plukker opp client-side renderet maincontent-element. Men det kan kanskje vente til den nye dekoratøren. Bare la denne issue'en være åpen så vi husker på problemstillingen. 😄
