### ISSUE TITLE
[BUG] Valg en engelsk i språkvelger vises flere ganger

### ISSUE THREAD

**Issue by KenAJoh** [navikt/nav-dekoratoren_legacy#1394]
## Replikere
- Nav.no -> Engelsk i footer
- Åpne språkvelger

<img width="1440" alt="Screenshot 2023-03-06 at 09 24 20" src="https://user-images.githubusercontent.com/26967723/223056352-4d8ebedc-5236-4336-9180-b8dcc4b5c17d.png">
<img width="1440" alt="Screenshot 2023-03-06 at 09 24 40" src="https://user-images.githubusercontent.com/26967723/223056361-681b2b9d-b848-4d57-9fb5-0cb8e8768365.png">

## Ekstra bug

På https://www.nav.no/en/home vil valg av øverste element i dropdown gi 404 https://www.nav.no/en/home/en?error

<img width="1440" alt="Screenshot 2023-03-06 at 09 27 26" src="https://user-images.githubusercontent.com/26967723/223056860-95360b1d-39e3-4b67-9976-fa40ab8164c4.png">

**Comment by anders-nom** [comment]
Hei! Dette var en bug i Enonic XP appen vår, som førte til en del feil i dataene den setter til språkvelgeren. Skal være fikset.

Vi håndterer ikke duplikate språkvalg i dekoratøren på noe vis, men det er kanskje noe vi bør vurdere. Laget en ny issue på det: https://github.com/navikt/decorator-next/issues/210
