### ISSUE TITLE
Kontrastverktøy i header

### ISSUE THREAD

**Issue by terjeofnorway** [navikt/nav-dekoratoren_legacy#1467]
Ref denne saken: Har det eksistert en kontrast-dropdown eller et verktøy i dekoratøren tidligere? https://jira.adeo.no/browse/FAGSYSTEM-286079

Diskutere om dette er nødvendig eller om de fleste som har behov for kontraster bruker Google High Contrast eller alternativer.
Se også kommentar om ønske om dark mode.

**Comment by ojnybo** [comment]
UU-teamet har sagt vi ikke skal tilby dette.
