### ISSUE TITLE
Engelsk meny bør ha samme overskrift og forside-lenke for alle målgrupper

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#1502]
Ettersom menyen er lik for alle målgrupper gir det ikke så mye mening å ha ulike overskrifter.

**Comment by eivindskifjeld** [comment]
Samme oppgave er opprettet av Terje. Lukker denne.

**Comment by eivindskifjeld** [comment]
https://github.com/navikt/nav-dekoratoren/issues/1503
