### ISSUE TITLE
Fokusmarkering ved Tab-navigering

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#380]
Vi legger til et step til i navigering som er Til SØK.
https://www-q0.nav.no/person/nav-dekoratoren/
Vi ønsker å kytte ut unødvendig tekst som til, gå til, eller hopp til så da blir følgende tekst per funksjonalitet:

- Hovedmeny
- Sideinnhold
- Søk

Så ønsker vi å legge til en icon som støtter opp under teksten, gi det mer visuell fokus.

Ordlyd “Gå til…

Vedlagt bilde er kun for å vise funksjonaliteten, ikke endelig visuelt design.
Fikser du det slik at ikke tab navigering flytter på innholdet. F.eks nå flyttes innhold når fokusmarkering er på logoen.

<img width="339" alt="fokusmarkering" src="https://user-images.githubusercontent.com/6075402/82806777-c66c1600-9e86-11ea-8240-5aba12fbe1ab.png">

**Comment by anders-nom** [comment]
Har endret teksten, og problemet med posisjonering ble fikset for en stund siden. Skissen for ikoner på skiplink er fra en gammel versjon som ikke passer inn i nåværende, så lar den ligge inntil videre (opprett evt. ny sak på det).
