### ISSUE TITLE
Optimalisering

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#382]

**Comment by Laier68** [comment]
**Da har jeg testet denne saken så godt som det lar seg gjøre i Q1**

Foretatt sjekk i Chrome og IE11 + pluss emulert mobilvisning i chrome.
1) Har sjekket relativt mange av NAV sine applikasjoner i Q1 og snust etter avvik spesielt mtp ting som brekker.  I tillegg til også sjekk i dekoratør/header/footer.
2) Av miljømessige grunner er ikke akt.plan og dialog veileder sjekket. (Ligger ikke i q1) 

Observasjoner *
a) Ser at jeg ikke kan aksessere **Kontakt oss** siden I IE11, får bare opp header/footer.
Fungerer OK i produksjon, Anders mente dette ikke var relatert til optimaliseringssaken.
(Ser at jeg kan klare å komme inn på tjenesten med litt frem og tilbake navigering)
b) Ser at **Dine foreldrepenger** fungerer suboptimalt i IE11, MEN tjenesten har samme issue i dagens produksjon. (de har også lagt inn varsel mht utdatert nettleser)
c) Ser at omriss av en boks i **meldekort** appllikasjonen vises ufullstendig når zoom er annet enn 100% (slik er det ikke i dagens produksjon) Dette skal i flg Morten J. ikke være relatert til optimaliseringssaken.
d) Ser at blant annet tjenesten Dine foreldrepenger får i splitt sekund litt grisete visning når side hentes. Det er samme tilfellet i produksjon mao heller ikke relatert til denne saken. 

![image](https://user-images.githubusercontent.com/60879532/84237750-3373e280-aafa-11ea-90df-ec0df3bec684.png)

**Comment by Laier68** [comment]
**Da har jeg tatt en kjapp verifiseringsrunde i produksjon etter prodsetting.**
Sjekket Iphone 11 / IOS 13, IE11 og Chrome.
--> Det oppfører seg helt OK såvidt jeg kan se.  Har spesielt sjekket de observasjonene som ble gjort i Q1 under test.
