### ISSUE TITLE
Lenke på logo, tar deg alltid tilbake til privat forside

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#387]
Klikker man på logoen, tar den deg tilbake til forsiden til privat, selv om man er på arbeidsgiver eller samarbeidspartnere.

Er dette riktig, eller skal den ta den til forsiden i den kategori inndelingen man er i? Har man valgt arbeidsgiver, tar logoen deg tilbake til arbeidsgiver forsiden.

**Comment by mjansrud** [comment]
Thea:

@chris_arnesen Hm, kan godt hende at vi skal sende bruker til startsiden for sin aktør/kontekst ettersom person/arbeidsgiver-velger ligger over. Logg-inn-knappen er kontekstavhengig, og da bør vel egentlig logoen også være det.

Litt research:
Ser at DNB, Sparebank1 sender deg til startsiden for bedrift hvis du har valgt bedrift. De har plassert person/bedrift-velgeren over logo slik som oss. KLP, Gjensidige, Storebrand og Nordea sender deg alltid til startsiden for privatperson uavh. av om du har valgt bedrift, men da har de person/bedrift-velger ved siden av og ikke over logoen.

Tanker @hannasofiahogberg @ingridhaland1 ?

**Comment by mjansrud** [comment]
Chris:

Men skal den ta deg til privat forsiden om man er på arbeidsgiver innhold? @theasteen

**Comment by mjansrud** [comment]
Thea:

Den skal alltid ta deg til nav.no (startsiden for nettstedet)

**Comment by mjansrud** [comment]
Ole Jonas:

@theasteen - Denne skal vel alltid gå tilbake til forsida?

**Comment by ojnybo** [comment]
Møte 09.06 - Høre med PO Arbeidsgiver om dette fungerer hos de. Vi beholder det som det er inntil videre. Er det mulig å sette opp en hotjar på de som trykker på logoen fra arbeidsgiver-siden?
