### ISSUE TITLE
nav.no får ikke med seg at sessjonen har timet ut

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#388]
Sessjonen har timet ut så hvis jeg prøver å velge noe i menyen kommer jeg til id-porten. Jeg har fortsatt "Ditt NAV" knappen synlig når jeg går tilbake fra ID-porten til nav.no.

<img width="1439" alt="Skjermbilde_2020-05-14_kl _10 34 26" src="https://user-images.githubusercontent.com/6075402/82810592-236bca00-9e8f-11ea-98f2-5703ac73a2c5.png">

Suboppgave: #573

**Comment by mjansrud** [comment]
Petter Lier:
Jeg har kjørt en test hvor sesjonen definitivt har timet ut. Siden du står på viser fortsatt innlogget header og Ditt NAV menyen er tilgjengelig. A) Gjør man en refresh (type F5) lastes siden og dekoratør inn pånytt og da er man selvfølgelig uinnlogget. B) velger man isteden å gå mot noen av tjenestene i Ditt NAV menyen rutes man til ID-Porten for innlogging, avbryter man dette og går tilbake (pil i browser) havner man på nav.no med uinnlogget header. Konklusjon , her er det samme oppførsel som i gml. dekoratør/header. Hvorvidt man burde lagt inn en mer aktivt sjekk før/ved utløp er annen sak. Derfor tyder det på at oppførselen Thea opplevde er tilstanden som er beskrevet i forrige kommentar. (Tilstand hvor OpenAM token er utløpt og OIDC token som lever)

**Comment by mjansrud** [comment]
Petter Lier:

@olejonasnyb1: Jeg sjekker litt på denne i forkant mht oppførsel. Ved refresh burde i hvert fall headermenyen gå til uinnlogget tilstand hvis sesjonen er utløpt. MEN mistenker vel at denne situasjonen kan ha utspring i ganske kjent problematikk hvor man kommer i tilstand hvor OpenAM token er utløpt og OIDC token som lever. Hvis det var tilfelle i dette caset oppfører dekoratøren egentlig som den skal og nøyaktig likt den gamle. Uheldig ja.

**Comment by Laier68** [comment]
Ref standup idag 23/6.  Poenget mitt i denne saken var at jeg mistenkte Thea (som meldte saken) hadde kommet i en tilstand hvor OIDC token lever mens OpenAM token ikke lever.  Det kan skje i enkelte situasjoner og er kjent problematikk!  Da vil oppførselen kunne være som skissert i saksbeskrivelsen.   @ojnybo @anders-nom @mjansrud 

31/8-20: Jeg la ut en videosnutt på slack til Ole Jonas/Anders og Morten. https://nav-it.slack.com/archives/GV98B6Y9Y/p1598536479046400  Der har man et case hvor man oppleves som innlogget av dekoratøren selvom det mangler et OIDC token (har riktignok et openam token som lever)

**Comment by Laier68** [comment]
Jeg la ut en videosnutt på slack til Ole Jonas/Anders og Morten. https://nav-it.slack.com/archives/GV98B6Y9Y/p1598536479046400 Der har man et case  hvor man oppleves som innlogget av sekoratøren selvom det mangler et OIDC token (har riktignok et openam token som lever)

**Comment by Laier68** [comment]
Oppsummert
Bruker kan komme i 2 ulike tilstander som begge er uheldig, rotårsaken er forskjellig varighet på openam token kontra oidc token.  
a) OIDC token lever men openam token er utløpt. 
b) Openam token lever etter at oidc token (>60min) er utløpt.   

Her er det pt ingen løsninger på det problemet. Hadde man kunnet skrotet openam hadde det løst saken.

**Comment by theasteen** [comment]
Relatert til https://github.com/navikt/nav-dekoratoren/issues/573

**Comment by terjeofnorway** [comment]
Vi skal på et eller annet tidspunkt forbedre utloggingsvarselet. Denne funksjonen er ikke optimal (les: fungerer ikke) slik den er i dag. Jeg lukker denne oppgaven.
