### ISSUE TITLE
Visning av navn i IE11 - ikon og navn kan gå litt inn i hverandre.

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#392]
![image (2)](https://user-images.githubusercontent.com/6075402/82811613-78a8db00-9e91-11ea-9dba-f97d8de295d2.png)

**Comment by mjansrud** [comment]
Greier ikke å reprodusere feilen, kan ha blitt fikset i en tidligere PR

**Comment by Laier68** [comment]
Verifisert OK 
![image](https://user-images.githubusercontent.com/60879532/84114111-107afd00-aa2c-11ea-945c-aa8ca48afe86.png)
