### ISSUE TITLE
Hengelås som ikon på alert-stripe for informasjon om Nivå 4 innlogging.

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#393]
Endre info ikon til hengelås i blått felt. Sort ikon.

**Comment by Laier68** [comment]
Tatt en kjapp sjekk i Q1 og Prod fra desktop og mobil det ser bra ut. 
![image](https://user-images.githubusercontent.com/60879532/84108819-6ac29080-aa21-11ea-858e-a0521234fbd6.png)
