### ISSUE TITLE
Tilgjengelighet og universell-utforming bør eller må ligge i footer

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#395]
Link til https://www.nav.no/no/nav-og-samfunn/kontakt-nav/teknisk-brukerstotte/nyttig-a-vite/tilgjengelighet-og-universell-utforming

Siden bør være lett tilgjengelig fra alle sider, så footer er i hvert fall ganske logisk sted. Denne typen informasjon pleier i tillegg å ligge i footer, så det er der folk forventer å finne det.

Det er ikke lovpålag enda. Men det kommer til å være lovpålagt å ha en tilgengelighetserklæring lett tilgjengelig per løsning.

**Comment by ghost** [comment]
Skisse forslag https://www.figma.com/file/jojeYYPeph1S9fiWW4dJXw/Footer?node-id=0%3A

**Comment by ghost** [comment]
Lenken er lagt til å sender deg til https://www.nav.no/no/nav-og-samfunn/kontakt-nav/teknisk-brukerstotte/nyttig-a-vite/tilgjengelighet
