### ISSUE TITLE
Plassering av logo i footer – Mobil versjon

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#396]
Skal stå over Arbeids- og velferdsetaten. Kan da også være noe større.
Nå henger den på "Les mer om databeskyttelse og informasjonskapsler.

**Comment by Laier68** [comment]
Sjekket litt på denne i Q1, NAV logo står nå over teksten "Arbeids- og velferdsetaten".  
Virker som alt er venstrestilt (sikkert riktig) vanskelig å vurdere om logoen er noe større.

![image](https://user-images.githubusercontent.com/60879532/84115426-5c2ea600-aa2e-11ea-898b-ac4c61823d1c.png)
