### ISSUE TITLE
Legge til lenke til teknisk brukerstøtte fra footer, nå som alfabetmenyen er borte?

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#398]
Innspill fra NKS.

Innspill om å lenke til teknisk brukerstøtte fra footer, nå som alfabetmenyen er borte?

https://www.nav.no/no/nav-og-samfunn/kontakt-nav/teknisk-brukerstotte

Bør den legges som en lenke i footer? På link linje med andre linker under kontakt oss tittel, eller bør den legges på kontakt oss siden?

Eller hører den hjemme et annet sted?

<img width="1788" alt="Screenshot_2020-05-18_at_16 46 43" src="https://user-images.githubusercontent.com/6075402/82812466-587a1b80-9e93-11ea-8b26-e4667618286b.png">

**Comment by mjansrud** [comment]
Tobias:

Hei

Tok en kjapp titt på tallene for sider om teknisk brukerstøtte

Den siden der får knapt 161 besøk i en uke. Ønsker vi virkelig å promotere den og isåfall hvorfor? Hvor mange etterlyser den? Fordelen er vel at den lar deg velge mellom personbruker og bedrift?

Til sammenligning får denne siden om innlogging for personbrukere rett under 6000 besøk hver uke
https://www.nav.no/no/nav-og-samfunn/kontakt-nav/teknisk-brukerstotte/hjelp-til-personbruker/innlogging_2_kap

Med andre ord, jeg tror det er denne siden folk egentlig er ute etter. Vi lenker til øverste side i den serien direkte fra Kontakt Oss appen.

Over 90% av de besøkene til siden om innlogging for personbrukere kommer rett fra Google, og 10% er direkte besøk

Dvs. Direkte trafikk = Folk som har vært på siden før, og som har lagret det som bokmerke eller fått en lenke på SMS av oss.

Jeg tror teknisk brukerstøtte innholdet er enkelt nok å finne på Google med andre ord.

Dersom det er et problem at vi sender folk rett til teknisk brukerstøtte for personbruker og ikke lar de velge mellom personbruker og bedrift så kan vi endre lenken fra "kontakt oss" appen, men jeg vet ikke om det vil hjelpe stort.

Det gir brukeren et ekstra klikk, og vi burde nok ikke gjøre det med mindre vi vet at bedrifter ender opp på den nye kontakt oss appen for personbrukere. Screenshot 2020-05-18 at 16.46.43.png

Hvis vi har et slikt problem burde vi også promotere et synlig valg i appen om å bytte mellom personbruker og bedrift for eksempel.

Se screenshots og vedlagte tall.

Pageviews = sidevisninger
Unique page views = sidevisninger per besøk
Entrances = antall besøk startet på denne siden
Source = trafikk-kilde

**Comment by mjansrud** [comment]
Thea:

Denne ligger på kontakt-oss-siden, så vi har jo tenkt at det holder. Kanskje vi skal få tak i noen besøkstall og legge det til grunn for hva vi gjør her? @tobiasmcvey5

**Comment by Olavrusten** [comment]
Et alternativ som vi bør vurdere, er å legge lenke under Kontakt i arbeidsgiverfooteren  rett til brukerstøtteinfo for arbeidsgivere. Fordi problemet er at forsiden på brukerstøtte, der du velger person eller bedrift, nå ikke er tilgjengelig noe sted. Så dette er litt kritisk egentlig. Jeg kan gjøre det raskt, hvis dere er enige i dette tiltaket.

**Comment by ojnybo** [comment]
Thea og Olav diskuterer dette alternativet med PO Arbeidsgiver
