### ISSUE TITLE
Søknadsveiviser ulik oppførsel

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#400]
Sak meldt av Chritain Haslund:

Når jeg står i søknadsveiviseren, https://www-q0.nav.no/soknader/nb/person/korona/sykepenger, og bruker navigasjon mellom Person og Bedrift i dekoratøren skifter det fra ny til gammel dekoratør.
Klikk på Arbeidsgiver i dekoratøren gir en helt annen oppførsel enn hvis jeg klikker på Bedrift nede i søknadsveiviseren. Ingen enkel fiks for dette, men en designutfordring.

![image](https://user-images.githubusercontent.com/6075402/82813163-cf63e400-9e94-11ea-9df1-9017c31bf3a6.png)

**Comment by mjansrud** [comment]
Thea:

Jeg diskuterte dette med Rune på teamet til Christian i går. Han påpekta at det er nyttig for brukerne å veksle mellom bedrift og person innad i søknadsveiviseren. Samtidig trenger vi at Arbeidsgiver-fanen i toppen sender bruker til startsiden til arbeidsgiver. Dermed får vi ulik oppførsel her.

I tillegg er ikke innholdet en-til-en mellom Bedrift og Arbeidsgiver hvilket kompliserer dette.

Rune og jeg kom fram til at vi lar søknadsveiviseren stå som den er inn til vi finner en god løsning.

**Comment by mjansrud** [comment]
Ole Jonas:

@theasteen @chris_arnesen her trengs det en designvurdering

**Comment by mjansrud** [comment]
Er enig i det Christian sier, de burde ha lik oppførsel. Trur ikke dette må fikses til i kveld, men vi kan jo ta det etter prodsetting en gang. Enten at søknadsveiviseren henter ut info fra cookien om hvilken context som er valgt, eller at søknadsveiviseren fortsatter med toggelen i appen og overstyrer contexten til også dekøratøren.

**Comment by theasteen** [comment]
Si ifra til Christian at oppførsel i dekoratør kan fikses ved hjelp av dekoratør-parameter

**Comment by Christian-Haslund** [comment]
Snakket med Rune Rosseland i dag. Denne saken kan lukkes.
Hvis det skal løses på en ordentlig måte må det gjøres omfattende endringer i søknadsveiviseren, både app og innhold. Det har vi ikke kapasitet til nå.
