### ISSUE TITLE
Tilbakemeldingsfunksjon i footer (ala gov.uk)

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#401]
La til skjermbilder for alle valgene. @chris_arnesen

Banneret spør "Is this page useful?" Du får 3 valg

Ja
Nei
Er det noe galt med denne siden?
Ja/Nei svar kan brukes til statistikk. Spørsmålet om noe er galt med siden kan vel fange opp både faktafeil og tilgjengelighetsfeil.

Merk også at de tilbyr både å sende en spørreundersøkelse på epost til brukeren, og at de kan fylle ut anonymt.

![01_gov_uk_is_this_page_useful](https://user-images.githubusercontent.com/6075402/82813394-41d4c400-9e95-11ea-8322-5cc7396fc20e.png)

**Comment by tobiasmcvey** [comment]
For denne oppgaven må vi også tenke på hvor vi skal lagre disse dataene slik at det blir enkelt å jobbe med de.

Jeg ønsker ihvertfall at vi kan sette svarene fra denne i kontekst med hvilken side brukeren var på, og vi kan kanskje også lagre om de var innlogget eller ikke og sikkerhetsnivå. Om vi ønsker å stille oppfølgingsspørsmål så trenger vi kontaktinfo.

Om dataene skal settes i kontekst med andre besøk så trenger vi også en ID per besøk. 

Gov.uk lar folk besvare en spørreundersøkelse også, og har 2 alternativer. Hvis man ønsker å svare anonymt så kan man det på en annen side, og man kan få tilsendt undersøkelsen på epost om man ønsker det. Det siste er fint for å la oss stille oppfølgingsspørsmål.

**Comment by tobiasmcvey** [comment]
Forslag på deler vi trenger

Vi trenger svar på 2 spørsmål

* Om folk finner det de leter etter. Derfor spør vi **Fant du det du leter etter?**
* Om det er noe galt med siden, faktafeil, tekniske feil, feil med universell utforming. Derfor spør vi **Er det noe galt med denne siden?**

Når delene løses, markér med x

Versjon 1
- [x] Avklare om dette er en del av dekoratøren eller separat app
- [x] Responsiv design for komponent
- [x] Universell utforming av komponent: Tastatur-navigering
- [x] Spørsmål 1 i Footer "**Fant du det du leter etter?**"  
- [x] Svaralternativer for **Ja** og **Nei**
- [x] Tekst og invitasjon med link til spørreundersøkelse etter Spørsmål 1 når man trykker **Ja** eller **Nei** (Hotjar survey)
- [x] Spore klikk på **Ja** og **Nei** i Amplitude, spore klikk på lenke til spørreundersøkelse

Før vi starter på 1.2 så bør vi avklare skal vi fortsette med Hotjar eller lage egen løsning for spørreundersøkelser og lagring av svar

Versjon 1.2
- [x] Logikk for oppfølgingsspørsmål til "**Fant du det du leter etter?**"  
- [x] Oppfølgingspørsmål
- [x] Radio buttons for svaralternativ
- [x] Spørsmål 2 "**Er det noe galt med denne siden?**"
- [x] Oppfølgingsspørsmål
- [x] Send inn svar
- [x] Spore klikk på radio buttons i Amplitude
- [ ] Fritekstfelt for "Annet"
- [ ] Spore trykk på "Send inn" av "Annet" i Amplitude - ikke friteksten! 
- [ ] Invitasjon til anonym spørreundersøkelse i Hotjar

Versjon 1.5
- [x] Felt for å legge til epost
- [ ] Logikk for å sende spørreundersøkelse til epost

Versjon 2
- [ ] Valgfritt alternativ: Send inn teknisk informasjon om din enhet for å hjelpe oss med feilsøking: operativsystem, nettleser, tidspunkt, skjermbilde av siden  

Avklaringer før vi starter:
- [ ] Skal dette være en del av Dekoratøren eller en egen app
- [ ] Trenger vi andre tjenester vi ikke har nevnt, f.eks en database for å lagre fritekstsvar og eposter
- [ ] Hvem må vi ha hjelp fra for ekstra tjenester? Hvem skaffer dette **før** sommerferien?

**Comment by ghost** [comment]
Sommerstudenter har dette som oppgave.

**Comment by theasteen** [comment]
"Epic" for https://github.com/navikt/nav-dekoratoren/issues/569 og https://github.com/navikt/nav-dekoratoren/pull/512. 
Gjenstående: Tilgjengeliggjøre svarene for andre team
