### ISSUE TITLE
Del skjerm med veileder – Stengt

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#403]
Er det mulig å se på en grafisk utforming, som gjør at tjenesten er stengt kommer tydligere frem?

<img width="637" alt="Del-ned_veileder_stengt" src="https://user-images.githubusercontent.com/6075402/82813540-8d876d80-9e95-11ea-84b6-272692614ff3.png">

**Comment by anders-nom** [comment]
Bruker rød Alertstripe:
![stengt](https://user-images.githubusercontent.com/18137669/83759084-4f4b3480-a673-11ea-9f61-422a6f38cd43.png)

**Comment by Laier68** [comment]
Har sjekket ut denne i Q1 fra forsiden og i et par app`er.
Ingen tvil lengre om at skjermdeling er stengt. (Presterte å lukke ved en "glipp of hand")

![image](https://user-images.githubusercontent.com/60879532/83938887-b8988800-a7d8-11ea-8f8a-a5fb51e5bee5.png)
