### ISSUE TITLE
Informasjon om bruk av cookies

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#404]
Plassering og tekstionnhold.
Hva skjer om man ikke godtar Cookies?
Funnet noen forslag, om dere kommer over gode eksempler, kan vi samle og diskutere.
Få inn info i footer under Personvern.

- [ ] Må innom juridisk (Heidi)
- [ ] Må vi ha "ja" og "nei"?
- [ ] Hva skjer hvis bruker sier "nei"?
- [ ] Hva er konsekvensen hvis app likevel samler inn?

**Comment by tobiasmcvey** [comment]
Juristen i team research ops har sagt at vi må se på cookie banner for navno igjen. 

 @ojnybo @TuvaSverdstad
