### ISSUE TITLE
Felles varselvisning på desktop/mobil

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#415]
Det er mye duplisert eller nesten-duplisert kode i komponentene for varselvisning på desktop og mobil. Implementer felles-komponenter for disse hvor mulig for bedre maintainability og optimisering.

**Comment by Laier68** [comment]
Da har jeg tatt en kjapp sjekk på varsel inkl. bjella i desktop og mobilvisning. (Emulert fra chrome) 
Det bra ut så vidt jeg kan se, Anders og tok dessuten en fellessjekk i safari/ios browserstack.
