### ISSUE TITLE
Breadcrumbs / brødsmulesti

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#431]

**Comment by ojnybo** [comment]
Hvis appene definerer det, kan brødsmulestiene være en del av dekoratøren. Forslag: Appene kan definere stien de ønsker å vise, forside og appnavn. Da kan appene styre selv hva de ønsker å vise. Har nav.no som start i brødsmule. Må finne en løsning for client-side rendra apper som fungerer med server-side rendra. Tvinger fram en diskusjon om informasjonsarkitektur.
