### ISSUE TITLE
Flytte varsler fra XP til dekoratøren

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren_legacy#445]
Hentes i Enonic XP idag. Kan de flyttes til dekoratøren for å gjøre de globale?

- [x] Utvikle frontend
- [x] Utvikle Endepunkt i XP

**Comment by PerOlavM** [comment]
Vi må lage et endepunkt i XP som data kan hentes fra (på samme måte som menyen).
Issue: https://github.com/navikt/nav-enonicxp/issues/414

**Comment by PerOlavM** [comment]
Endepunkt laget i egen branch. Avventer oppgradering av XP før vi bygger.
Testdata:
[{"heading":"Test driftsmelding","url":"/no/driftsmeldinger/test-driftsmelding","type":"prodstatus"},{"heading":"Korona skaper høy trafikk","url":"/no/driftsmeldinger/korona","type":"info"}]

**Comment by PerOlavM** [comment]
https://www-q1.nav.no/_/service/no.nav.navno/driftsmeldinger

**Comment by Laier68** [comment]
Påbegynt litt test av denne. 

Funn: 1) Ser at jeg man rutes til feilside når man går mot varslene fra apper som utbet.oversikt, veilede arb.søker, mfl.  Type ditt NAV, MK, mfl  ruter korrekt.  Morten er på saken !

**Comment by Laier68** [comment]
Da har jeg tatt en runde i portalen (Q1) inkl et sett av app`er. Det er gjort stikkprøvemessig i Chrome, IE, Firefox Edge, Safari, mfl. Vært innom noen ios`er og android versjoner. Alt virker OK ut sånn jeg vurderer det.
