### ISSUE TITLE
Varsel - gamle/usupporterte nettlesere

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren_legacy#448]
Fra Ståle Kjone: _Siste hovedversjon av de mest brukte nettleserne Chrome, Firefox, Edge og Safari. IE11 er ikke blant disse lenger.
Og så kommer det jo skjermlesere som Jaws, NVDA, VoiceOver (iOS) og Talkback (Android) i tillegg til disse.Det bør lages en sjekk med tilhørende melding til brukere av IE11 (og eldre versjoner) med en tydelig oppfordring om å oppgradere til Edge eller annen og bedre nettleser. Mulig dette bør gjøres på Dekoratør-nivå (felles header og footer)?_

Spørsmål fra @chrisarnesen 
_Holder det at vi lager en popup? Modal med info om å oppdatere til nettleser? Og kode som kontrolerer om du sitter på det?
Men kan vi kreve at våre brukere sitter på det siste av det siste?_

Svar fra Ståle K
_Ja, det stemmer vel. Var i kontakt med Monica M om dette temaet i går ifm Tolkebestilling på Salesforce-plattformen. Regner med at det kommer derfra?
Digipost med flere har tilsvarende løsning, og jeg trodde vel egentlig at vi allerede hadde dette ute på noen av tjenestene våre. Snakket om dette med Per Olav og Tobias i sin tid også.
Tanken er å luke ut verstingene, som IE11, for jeg er enig i at vi ikke kan kreve at alle sitter på siste versjon av en nettleser alene eller koblet mot en skjermleser.
Grunnen er at flere team fortsatt forholder seg til bl.a. IE11, noe som krever sabla mye ekstra testing og tilleggskode for å få det til å snurre og gå. Mye innsats for snaue 2,5 % av brukerne våre.
Hvordan dere ønsker å løse det, bestemmer dere. En pop-up som fungerer og er helt UU, kan være en løsning._ 

whatismybrowser.com

Gov.uk har også tilsvarende sjekk for tilpasning av nettsidene sine for blant annet IE 7, 8 og 9. Tung vei å gå dersom vi skal støtte mer enn en til to hovedversjoner av en gitt nettleser.
Ellers ligger det noen eksempler på implementering av dette ute på Github. Se https://github.com/browser-update/browser-update

**Comment by Laier68** [comment]
Påbegynt test av denne. Det er et issue med subdomener, X`er man ut mld fanges ikke det opp i hele nav.no portalen.  Anders fikser saken.

**Comment by Laier68** [comment]
Jeg har sjekket følgende: **1)** Tatt noen **stikkprøver i diverse apper** for å se at det ikke noen negativ påvirkning av mld som vises i IE11 (Ditt nav, meldekort, søknadsdialoger. innboks, utbetoversikt, aktplan, saksoversikt, dine foreldrepenger, ditt sykefravær, personopplysninger, hva er din situasjon, forsiden på nav.no, koronaveivser,  skjemaveiviser mfl)  **2)** Sjekket at mld lar seg fjerne/ X`e ut (Et issue mtp subdomener observert, ref. kommentar over) **3)** Sjekket at mld ikke dukker opp i andre nettlesere inkl eldre versjoner av IE edge.

**Comment by Laier68** [comment]
Tatt en sjekk i produksjon etter prod.setting, visningen ser ok ut.  Men ser ikke ut som det å fjerne varsel fanges helt opp i rundt om i portalen.  Ingen stor sak sånn jeg vurderer det men nevner det. (Dette var på bordet før ferien også)
