### ISSUE TITLE
Felles komponenter for header-linje

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#455]
Mobil/desktop visning i headeren har mange unødvendige duplikater/nesten-duplikater, både scripts og DOM-elementer. Bruk felles komponenter hvor det er mulig.

**Comment by Laier68** [comment]
Da har jeg tatt en kjapp regresjonssjekk av header/mobil meny i Q1. Det ser ok ut, jeg reagerer ikke på noe spesielt ihvertfall, tab navigering i headermenyene fungerer bra.  Sjekket i safari (ios) og Chrome (android) pluss mobil emuleringer i chrome/firefox.
