### ISSUE TITLE
Flytte Chatbot Frida til dekoratøren

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren_legacy#456]
Sørge for at chatboten blir en del av dekoratøren. Idag importerer de enkelte appene chatboten som en NPM-pakke i egne apper.

Tanken er at det kan være parameterstyr. Som default skal chatboten være skrudd av, men den skal være aktiv hos  Koronaveiviser, Familie.nav.no, Meldekort og Min side arbeidsgiver. På sikt vil den kunne rulles ut til flere apper.

**Comment by Laier68** [comment]
**Liten oppsummering av test.**

1. **Navigering i nav sfæren**. Frida kan aktiveres fra noen definerte steder/apper.  Men man vil da ha med seg Frida rundt i hele nav.no portalen inntil man avslutter dialogen/sesjonen. (Frida vil dog ikke fjernes umiddelbart når man avslutter en dialog men ved en refresh eller ved at man går til en "ny side" )  Frida vil ikke vises på Arbeidsplassen da de ikke benytter seg av dekoratøren.     
--> Navigering i portalen OK sånn jeg vurderer det.
2. **Navigering utenfor nav sfæren**. Hvis man starter opp en Frida dialog/sesjon og beveger seg utenfor nav sfæren vi sesjonen løpe og kan fortsettes hvis man går tilbake til nav.no sfæren. (Sesjonen løper inntil den avsluttes, timer ut eller lukker nettleser) 
Det medfører at man kan uinnlogget starte en Frida dialog, logge inn underveis via ID-Porten og fortsette dialogen etter at man har returnert til nav.no (innlogget)  
--> Testet OK sånn jeg vurderer det.
3. **Browserer/Plattformer:** Har tatt en sjekk i ulike browsere (Chrome, Firefox, Opera, Edge, Vivaldi og IE11) det ser OK ut. 
      Stikkprøvemessig foretatt noen tester i ulike IOS/android versjoner, ulike enheter (Iphone/Samsung-Ipad/Tablet) 
--> Testet OK sånn jeg vurderer det.
4. **Uinnlogget / Innlogget modus**. 
-->Det ser ut til å fungere som det skal dvs upåvirket av om man er innlogget eller ikke.

Det har underveis vært noen få justeringer/fikser, har dok i slack tråd https://nav-it.slack.com/archives/GT542SFN1/p1597242371003100
