### ISSUE TITLE
Optimalisering / code-splitting

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#509]
Implementere code-splitting og dynamisk lasting av komponenter for å redusere dekoratørens innlastingstid.

**Comment by theasteen** [comment]
Tricky å få til hvis man har både client-side og server-side-rendring (ref. @mjansrud  & @anders-nom ).
"File-splitting + client.js henter inn alle chunker dynamisk uten at man legger det som en del av HTML-en"
