### ISSUE TITLE
Hopp over (Gå til) tab navigering

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#515]
Hopp over (Gå til) tab navigering.
Nå vises kun «Hovedmeny» og «Søk».
Hopp til «Hovedinnhold» har falt ut.

Alle 3 har tidligere vært valg for sluttbruker.

**Comment by ojnybo** [comment]
Lukker denne saken, da det vist seg at det antageligvis bare var cache hos Chris. Fungerer fint.

**Comment by anders-nom** [comment]
Endret denne for en liten stund siden slik at "hovedinnhold" kun vises på sider som har #maincontent id'en, mulig det er årsak til forvirringen.
