### ISSUE TITLE
Fant du det du lette etter? – Versjon 2

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#569]
Se på forbedring av arbeidet sommer studenter har utført.
Hva har vi lært så langt av bruken av den?
Se på tekster og forbedre innhold.
Ta en vurdering på hvilken sider den skal ligge på. Skal den ligge på alle sider? Trenger den f.eks å ligge på forsiden?

Brief
#401 (comment)

**Comment by chrisarnesen** [comment]
Brief
https://github.com/navikt/nav-dekoratoren/issues/401#issuecomment-644098434

**Comment by Olavrusten** [comment]
Overordnet: 
- Bør "Fant du det du lette etter" kun plasseres på innholdssider, ikke på forsiden? Gir liten mening å ha denne modulen på forsiden?
- Bør "Meld om feil og mangler" ligge helt nederst i dekoratøren (på linje med logo, Arbeids- og velferdsetaten osv.)? Det gjorde den vel tidligere? Jeg synes den har feil plassering nå: "Meld om feil og mangler" sammen med "Fant du det du lette etter" bryter opp forsiden slik at du mister flyten.

Innhold "Meld om feil og mangler":
- Jeg mener vi må ha et fritekstfelt, der brukeren kan fortelle hva slags feil hen opplever. Uten fritekstfelt er kanalen verdiløs for NAV, og gir ikke mening for brukeren. Jeg synes bestemt å huske at vi hadde et fritekstfelt i forrige versjon? Er det noen som husker hvordan det var, og ble tilbakemeldingene sendt til og sortert av brukerstøtte i NAV? Aksel husker kanskje?
- I forrige versjon var det også mulig å gi tilbakemelding på feil eller mangler i innhold på nav.no. Den kategorien har vi fjernet nå, fordi den blir spesielt meningsløs uten et fritekstfelt. Får vi et fritekstfelt, kan vi legge til denne kategorien igjen, hvis vi ønsker.

Innhold "Fant du det du lette etter"
- Vi har per nå landet på noen kategorier hvis du svare nei: innholdet var ikke relevant for meg, jeg forstod ikke innholdet, innholdet var lite oversiktlig. Vi bør tenke på om det er andre og/eller bedre kategorier som kan gi oss mer verdi tilbake.

**Comment by ghost** [comment]
UU_Teamet håper UU også kan komme inn som eget alternativ dersom man svarer NEI på dette spørsmålet. F.eks. “Innholdet blir ikke lest opp på mine tekniske hjelpemidler”

Vi kan komme med et bedre forslag til kortere og bedre ordlyd.

**Comment by tobiasmcvey** [comment]
@idaons og jeg ser på hvilke data vi skal lagre. Vi plukker opp denne tråden igjen neste uke @chrisarnesen @Olavrusten 

Vi skal ha fritekst med databasen men vi trenger ikke så mange spørsmål og kategorier for å få nyttig informasjon.

Her er den opprinnelige beskrivelsen vi skulle lage
https://github.com/navikt/nav-dekoratoren/issues/401
