### ISSUE TITLE
Mobil løsningen brekker på 340 px

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#570]
Løsningen brekker på 340 px. 

Innhente tall på hvor mange som bruker løsningen på 320 px. 

Knapper bryter på små skjermer.

Hvilken skjermoppløsning skal vi legge oss på.
Bruker noen av sluttbrukerne mobiltelefoner som er under x antall pixler?

**Comment by tobiasmcvey** [comment]
Jeg trenger mer info her. Er det skjermstørrelse eller nettleserstørrelse det er snakk om her? Oppdaget vi problemet eller er dette innrapportert? 


Det er 17,784 kombinasjoner av skjermstørrelse og nettleserstørrelse på nav.no for de siste 7 dagene. Det er mye variasjon selv om mobilen kan ha lik skjermstørrelse.

Litt flere enn 11,000 brukere har enheter med 320x pixler i skjermstørrelse. 

Deres nettleser har en annen størrelse. Dette er de 2 mest populære kombinasjonene for så små enheter.

| Skjermstørrelse | Nettleserstørrelse | Brukere |
| -----: | -----: | ---: |
| 320x568 | 320x450 | 9,207 |
| 320x568 | 320x440 | 2,001 |

De fleste har en mye større skjerm. [Malen til rapporten i Google Analytics](https://analytics.google.com/analytics/web/template?uid=JRAdfUNlRMe00n1JvDfzCA).

**Comment by tobiasmcvey** [comment]
Litt mer info for designere
https://css-tricks.com/google-analytics-can-show-screen-resolution-%E2%89%A0-browser-window/

**Comment by ghost** [comment]
Testet ut litt, det ser nå ut til at det ikke knekker/bryter før om man har en nettleser på mindre enn 288 px.

**Comment by ghost** [comment]
Ida har fikset utfordringen.
