### ISSUE TITLE
Utloggingsvarsel med fornying

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#573]
Dette er en gammel oppgave som opprinnelig hadde andre forutsetninger. Derfor kan noen av kommentarene og skissene være utdatert.

## Nye skisser
https://www.figma.com/file/looUxAQFs0nJcpFsUxQpcF/Global-Utloggingsvarsel?type=design&node-id=1065-3819&mode=design&t=z326x67rXVmDMSSj-4

## Ny funksjonsbeskrivelse 
- Bruker skal kunne fornye innlogging med 1 time avgangen.
- 5 minutter før login utløper skal bruker se et varsel.
- Brukeren kan velge mellom å fortsatt være logget inn og logge ut.
- Det er ikke mulig å ignorere varselet - brukeren må ta ett valg.
- Dersom brukeren ikke tar et valg (lar nettsiden stå oppe) vil hen bli sendt til en "du er utlogget"-side.
- En såkalt "session" varer i 6 timer. Dette er rammen som brukeren kan fornye login innenfor.
- Når de 6 timene har utløpt vil brukeren få beskjed om å logge inn på nytt.

## Dokumentasjon for Wonderwall og refresh tokens
https://docs.nais.io/appendix/wonderwall/?h=refresh#51-refresh-tokens

**Comment by Laier68** [comment]
Noen eksempler fra apper som har former for utloggingsvarsel .

Meldekort 
![image](https://user-images.githubusercontent.com/60879532/107111984-8605ca00-6854-11eb-9fcd-4c1653120412.png)

Ditt NAV har en variant.  
![image](https://user-images.githubusercontent.com/60879532/107111312-733cc680-684f-11eb-956c-9eee3f904027.png)

Ditt sykefravær
![image](https://user-images.githubusercontent.com/60879532/107111540-31148480-6851-11eb-8f95-246754d9d466.png)

Søknadsdialoger (AAP, mfl)
![image](https://user-images.githubusercontent.com/60879532/107111626-df202e80-6851-11eb-89e5-1c3bac71373b.png)

Dialog  
![image](https://user-images.githubusercontent.com/60879532/107113641-83a96d00-6860-11eb-9c57-b2b3dc072e50.png)


Det er ganske forskjellig hvilken logikk som benyttes for når disse varslene skal trigges.

**Comment by Laier68** [comment]
**Hvordan teste denne saken.**
Jeg kommer til å dokumentere funksjonell test av denne saken her. Det er noen ulike case man bør ha sjekket inkl. noen cornercase varianter.  
https://confluence.adeo.no/pages/editpage.action?pageId=402024033

**Comment by Laier68** [comment]
Dette kommer ikke noe varsel i dev miljøet jfr slack tråden
https://nav-it.slack.com/archives/C01URBQ5CV9/p1623652585012100

Selve testingen blir dokumentert her:
https://confluence.adeo.no/pages/editpage.action?pageId=402024033

**Comment by terjeofnorway** [comment]
Oppdatering etter backlog grooming 18/10/22:
ID-porten støtter fortsatt ikke refresh tokens, så vi avventer utloggingsvarsel til vi kan tilby dette som en funksjon. Vi er klar over at mangel på mulighet til å fornye innlogging muligens bryter med UU-krav.
