### ISSUE TITLE
Refaktor av varsler til å hente json og ikke html

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#602]
- Varsler hentes som html, som gjør det vanskeligere å implementere / endre eget design
- Refaktorer varsler: Hent data som json og design etter eget ønske

**Comment by Laier68** [comment]
Saken står standby testmessig inntil det kommer en løsning i saken med at varsler ikke fungerer (meldt i kanal: team-dokumentløsninger) i q1.  Det kan selvfølgelig også vurderes om vi trenger å teste det å generere nye varsler.  Det er er selvfølgelig  en opsjon det, men det blir en sannsynlighets/risiko vurdering @ojnybo.

**Comment by Laier68** [comment]
Test av eksisterende varsler
10108000398 Har et sett med gml varsler liggende.
- Det vises korrekt 5 varsler når det er flere og lenke vises til varsdelinnboks.
- Det vises korrekt 1 varsel nå det kun er et innenfor 1år, ingen lenke vises. (jfr 4)
- Tekst ser OK ut.
- Url ser OK ut
- Timestamp ser OK ut. (jfr 1 og 3)
- Visning ser OK ut.
1)
![image](https://user-images.githubusercontent.com/60879532/93660069-99ea9400-fa4b-11ea-8189-5c5bded0c8f0.png)
2)
![image](https://user-images.githubusercontent.com/60879532/93660136-2301cb00-fa4c-11ea-9b10-1409e9964dc2.png)
3)
![image](https://user-images.githubusercontent.com/60879532/93660175-770caf80-fa4c-11ea-9bb4-cedcbd4e6cf6.png)
4)
![image](https://user-images.githubusercontent.com/60879532/93660455-6a3d8b00-fa4f-11ea-83c0-f9836e4f3bc9.png)

**Comment by Laier68** [comment]
Saken står standby testmessig inntil det kommer en løsning i saken med at varsler ikke fungerer (meldt i kanal: team-dokumentløsninger) i q1. Det kan selvfølgelig også vurderes om vi trenger å teste det å generere nye varsler. Det er er selvfølgelig en opsjon det, men det blir en sannsynlighets/risiko vurdering @ojnybo.

**Comment by Laier68** [comment]
Etter en lang kamp fungerer nå varselkjeden  i Q1. Mao kan vi gjøre ny test av denne saken hvis den fortsatt er aktuell og prioritert.

Følgende bruker har et varsel i Q1 :  07128621770
Følgende bruker har flere varsler (2stk) varsel i Q1 :  10108000398

**Comment by Laier68** [comment]
Da har jeg tatt en bred test og funksjonelt oppfører alt seg fint i bjella ved nye varsler.   
1) Telle indikatoren fungerer som den skal  
2) Når man har vært inne på bjella ved nye varsler, fjernes korrekt markering av nye/nytt varsel.  
3) Jeg har testet at lenken "Vis alle varsler" dukker opp når det eksisterer >5 varsler.
4) Sjekket at mld i varselbjelle viser kronologisk og har rett timestamp
5) Sjekket at varsel url en på en mld i bjella fører korrekt frem til aktuell mld. 
6) Ser at visningen av https://www-q1.nav.no/dekoratoren/api/varsler/rest/varsel/hentsiste  er kjemisk ren for html. 
Q1: 
![image](https://user-images.githubusercontent.com/60879532/95850483-305f5c00-0d51-11eb-98f1-c5959a187a8d.png)

Prod:
![image](https://user-images.githubusercontent.com/60879532/95850747-9815a700-0d51-11eb-980d-5273d108c285.png)

**Comment by Laier68** [comment]
Saken er prodsatt 14/10 ca kl. 07.50
Det fungerer som et skudd fra et funksjonelt ståsted. Sjekket eksisterende varsler og sendt et nytt varsel.  Formatet er nå JSON.
Sjekket varsler på egen bruker i produksjon.
