### ISSUE TITLE
Dekoratøren: UU-forbedringer

### ISSUE THREAD

**Issue by ojnybo** [navikt/nav-dekoratoren_legacy#620]
Melding fra UU-teamet:
UU-teamet ønsker å bidra, så vi har nylig kjørt en ny automatisk validering av nav.no/person med fokus på kodekvalitet og krav til universell utforming av IKT. Valideringen (med SortSite v5.37 macOS) avdekker en del potensielle feil eller mangler (ikke uttømmende og potensielle falske-positiver), hvor noen kan være i globale elementer som dekoratøren.
Fint om noen har tid og anledning til å se på dette rimelig raskt, da tilsynet er rett rundt hjørnet. Anbefaler å bruke [rapportene fra SortSite (Sharepoint)](https://navno.sharepoint.com/sites/universellutformingavikt/SitePages/Validering-av-nav.no-august-2020.aspx) og utvidelsen [ARC Toolkit ](https://chrome.google.com/webstore/detail/arc-toolkit/chdkkkccnlfncngelccgbgfmjebmkmce)(til f.eks. Chrome) til dette arbeidet.

**Eksempler:
Megamenyen/Hamburgermenyen
Flere forekomster av Section:“” (blank)**
ERR<section id="decorator-header" role="main" class="navno-dekorator with-context" data-hj-suppress=""></section>type: SECTION[main]label:
multipleMainLandmarks - Error: Multiple main landmarks are present. Screen reader users will not know where the main content is - Recommend: Remove all but one of the main landmarks

**Gjenbruk av ID-er**
ERR<h2 id="venstrelenker-overskrift" class="typo-undertittel menylenker-overskrift">Kontakt</h2>ID: venstrelenker-overskrift
duplicateIdUsed - Error: Duplicate IDs used - Recommend: Most screen readers will only use the first ID found
ARIA-labelledby
ERR<ul aria-labelledby="venstrelenker-overskrift" class=""></ul>aria-labelledby=venstrelenker-overskrifttag: UL
ariaLabelledbyOnNonInteractiveElement - Error: aria-labelledby is used on an element which does not reliably convey this attribute - Recommend: Put aria-labelledby on an active element or an element with a role defined, or use visually hidden text instead

NB! Ingenting er bedre enn at dette er falske-positiver, men det må noen av dere som kan koden best verifisere.
Se [Validering av åpne sider og filer på nav.no - august 2020 (Sharepoint).](https://navno.sharepoint.com/sites/universellutformingavikt/SitePages/Validering-av-nav.no-august-2020.aspx)

**Comment by anders-nom** [comment]
Nevnte eksempler er fikset, kan undersøke mer til uka. For apper som har implementert dekoratøren ved å sette inn `<section>` tags for header og footer, må `role='main'` attrib'ene fjernes i de enkelte appene.

**Comment by PerOlavM** [comment]
Visning av driftsmeldinger - Advarsel fra ARC på ikon:
WARN svg Focusable - Warning: SVG is focusable - Recommend: Set focusable='false'
![image](https://user-images.githubusercontent.com/35491554/91438830-49c54b00-e86c-11ea-9150-f84502ba3969.png)
