### ISSUE TITLE
Lag et parameter for påkrevd innloggingsnivå 

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#628]
- Send brukeren til loginservice dersom brukeren ikke er logget inn med ønsket innloggingsnivå.

**Hvorfor?**
I dag implementeres egne løsninger for å automatisk sende brukeren til loginservice. Denne funksjonaliteten kan legges i dekoratøren slik at teamene slipper å lage egne løsninger.

**Comment by Laier68** [comment]
Testet med ulike varianter:
1) Logget inn på fks ditt nav med nivå 3 bruker -> Går mot PO url -> step up til nivå 4-> innlogget PO nivå 4. (Rett nivå fanges opp i endepkt Auth og i ditt nav menyen) **OK**
2) Gått direkte mot PO ->Innlogging viser kun nivå 4 alternativ-> Logger inn PO. **OK**
3) Logget inn på fks ditt nav med nivå 4 bruker -> Går mot PO url -> Rett inn på PO nivå 4. **OK** 

4) Logget inn direkte på utbet.oversikt nivå 3 (kun openam token)  ->  Går mot PO url -> step up til nivå 4-> innlogget PO nivå 4. 
Her er det en feil i produksjon, etter stepup oppfattes ikke alltid sesjonen som den er med nivå 4 (i auth og dittnav menyen) PO applikasjonen oppfatter korrekt at bruker faktisk er inne med nivå 4) Det er en feil ifm tokenveksling i slike tilfeller, benyttes openam/esso token (n3) istedenfor oidc token (n4) for å avgjøre sikkerhetsnivå. (Dette har ingen praktisk betydning for om bruker kommer inn på n4 tjenesten! )

Ser i etterkant at case 4) feilen slår litt uheldig ut ifm vår endring, bruker kan i dette tilfellet kommer i en loop ved overgang mot PO.  Det gjør at vi avventer med å endelig legge ut endringen (Team Ditt NAV jobber med et nytt endepkt Innloggingsstatus (PB-470) som skal på sikt ta over for Innloggings-api.  Da skal dette kunne løses ved at dekoratøren da vil få riktig  sikkerhetsnivå også i case 5.
 
Avventer mao til PB-470 er prodsatt. Tar opp igjen casene da.

NB: Ble også i denne saken foretatt diverse innlogginger som i pkt 1) med edge, chrome, IE11, Firefox, iphone11 ios/safari 13, Samsung 20 android 10  /chrome. **Alle OK forløp.**

**Comment by Laier68** [comment]
Team Ditt NAV er nå ferdig med det nye endepkt Innloggingsstatus (PB-470)

**Comment by Laier68** [comment]
Denne saken og sak https://github.com/navikt/personopplysninger/issues/211 testes samtidig. (2 sider av samme sak)
Case`ene er hentet fra testen som ble gjort 2/9 jfr kommentar

1) Logget inn på fks ditt nav med nivå 3 bruker -> Går mot PO url -> step up til nivå 4-> innlogget PO nivå 4. (Rett nivå fanges opp i endepkt Auth og i ditt nav menyen) **OK**
2) Gått direkte mot PO ->Innlogging viser kun nivå 4 alternativ-> Logger inn PO. **OK**
3) Logget inn på fks ditt nav med nivå 4 bruker -> Går mot PO url -> Rett inn på PO nivå 4. **OK** 

Case 4) feilet tidligere testrunde 2/9
4) Logget inn direkte på utbet.oversikt nivå 3 (kun openam token) -> Går direkte mot PO url -> får ikke opp stepup bildet men kun std nivå 4 innloggingsbilde-> Logger inn med nivå 4 --> Alt OK innlogget PO nivå 4.

Avvik: 
Jeg ser at jeg ikke får stepup skjermbildet i ID-Porten dvs får ikke dette 
![image](https://user-images.githubusercontent.com/60879532/99871016-a3bd7e80-2bd7-11eb-88b4-6383e745b413.png)
men dette
![image](https://user-images.githubusercontent.com/60879532/99871022-b768e500-2bd7-11eb-96c7-29a74ba6a660.png)

Jeg har sjekket hvordan dette oppfører seg i produksjon, der kommer man til stepup skjermbildet ved å trigge samme case.

Oppsummering:
Bortsett fra den lille twisten med med det manglende stepup skjermbildet i case 4) oppførte alt seg OK mht Personopplysninger.

MEN at det har fungerer OK mht til PO gjør ikke at jeg kan være 100% sikker på hva som skyldes "gml oppsett" og hva som tilskrives den nye parametersettingen.  I hvert fall bør de teamene som skal benytte dette teste selv også. 

Det jeg ikke har testet er hvordan dette påvirker en nivå 3 tjeneste, skal det da settes parameter også? eller er dette bare settes for nivå 4 tjenester?
