### ISSUE TITLE
Chatbot på nav.no

### ISSUE THREAD

**Issue by anders-nom** [navikt/nav-dekoratoren_legacy#645]
- Gradvis utrullering av Chatbot Frida på alle Enonic-sider.
- Målinger i chatbot'en?

**Comment by tobiasmcvey** [comment]
Endre målinger i Chatbot Frida

Idag starter målinger når en bruker avslutter chat

Vi ønsker å endre spørsmålene til [forslagene våre](https://navno-my.sharepoint.com/:w:/r/personal/tobias_mcvey_nav_no/_layouts/15/Doc.aspx?sourcedoc=%7BE7FC43EE-3DBF-47C4-A25A-2967DAD1C6C3%7D&file=Frida%20chatbot%20m%C3%A5linger.docx&action=default&mobileredirect=true)

**Spørsmål 1: Fikk du svar på det du lurte på?**
Svaralternativer: Ja, Nei, Delvis
Kodes som radio buttons
Logg event til Amplitude 

Event-type: tilbakemelding
komponent: chatbot
spørsmål: Fikk du svar på det du lurte på
svar: Ja, Nei, Delvis

**Spørsmål 2: Hva var det du lurte på?**
Svaralternativer:

- [ ] Levere sykemelding 
- [ ] Sjekke eller oppdatere aktivitetsplanen 
- [ ] Sjekke status eller følge opp sykemelding 
- [ ] Sjekke status på søknaden eller saken min 
- [ ] Sjekke status på utbetalinger 
- [ ] Sende meldekort 
- [ ] Sende skjema eller søknad 
- [ ] Sende melding eller svar til NAV 
- [ ] Lese meldinger fra NAV 
- [ ] Finne informasjon og forstå mine rettigheter 
- [ ] Finne ledige stillinger eller søke jobb 
- [ ] Finne statistikk, analyse eller forskning 
- [ ] Sjekke eller oppdatere oppfølgingsplanen 
- [ ] Annet

Logg event til Amplitude
Event-type: tilbakemelding
komponent: chatbot
spørsmål: Hva var det du lurte på
svar: toppoppgaver

Kodes som checkboxes så folk kan velge flere oppgaver

**Spørsmål 3: Er du fornøyd med hjelpen du fikk?**
Svaralternativer: 

- [ ] Jeg er veldig fornøyd
- [ ] Jeg er fornøyd
- [ ] Jeg er misfornøyd
- [ ] Jeg er veldig misfornøyd

Kodes som radio buttons så folk må velge

Logg event til Amplitude
Event-type: tilbakemelding
komponent: chatbot
spørsmål: Er du fornøyd med hjelpen du fikk
svar: tilfredshet


**Når bruker åpner, lukker og avslutter chat**
Logg Amplitude event
Event-type: chat-åpen, chat-lukket, chat-avsluttet
komponent: frida

**Comment by tobiasmcvey** [comment]
@anders-nom kan du lage dette i test? jeg kan hjelpe til om du trenger noe med Amplitude

**Comment by Laier68** [comment]
Foretatt en lettvektstest av Chatbot Frida
1)  Sjekket at hovedfunksjonalitet er intakt i selve app`en, den skal heller ikke være berørt av endringene.
2)  Endret tilbakemeldingsform. 
Den nye tilbakemeldingsformen påvirker såvidt jeg kan se ikke noe funksjonalitet (tenker spesielt på minimering av chatvindu, restart av chat og avslutte chat)
![image](https://user-images.githubusercontent.com/60879532/92686274-9fecc080-f339-11ea-8597-a1b1e8fa820b.png)
![image](https://user-images.githubusercontent.com/60879532/92688288-628a3200-f33d-11ea-963c-17f1307abf4a.png)
![image](https://user-images.githubusercontent.com/60879532/92692284-37571100-f344-11ea-80f7-5cac94fe9383.png)


**Diverse:** 
A) Ser at teksten på spm 2 er: Hva kom du hit for å gjøre?
mens tekst forslaget til Tobias i denne saken var:  Hva var det du lurte på?
--> Men det kan vel skyldes at saken ikke er oppdatert 
**NB: Har sjekket med Tobias nå, teksten er OK.** 

B) Ser at IE11 ikke lengre takler infoboksen "Er du sikker på at du vil avslutte" 
Vi signaliserer jo at vi ikke støtter IE11 lengre, og bruker kan benytte benytte "haken" og "krysset" selv om det ser litt grumsete ut.  
![image](https://user-images.githubusercontent.com/60879532/92687660-4639c580-f33c-11ea-854d-c3c918dcfb33.png)

C) Feilmeldinger når manglende det mangler input i tilbakemeldingsskjemaet er på formen. Den er vel greit nok! 
![image](https://user-images.githubusercontent.com/60879532/92688531-ca407d00-f33d-11ea-9fab-b714b5ab24cc.png)

**Comment by Laier68** [comment]
Saken ble testet på torsdag morgen, fikk ikke sjekket ulike devicetyper i browserstack. Viste seg at det ble trøbbel med visning/formattering i Safari.  (Viste seg også at det var trøbbel med visning av Frida i Q1 browserstack, dette er testmiljøbetinget/browserstack relatert men ville mao vært vanskelig å avdekke bug`en uansett i test)
Saken ble rettet OK samme dag. 
![image](https://user-images.githubusercontent.com/60879532/92867988-8b73fb00-f401-11ea-9a02-fc9fec6b4344.png)

**Comment by Laier68** [comment]
Gjenstår en liten bug mht en litt avkuttet visning av Frida ikonet i safari. Lager en liten separat bug sak på det #667
