### ISSUE TITLE
Frida ikonet kuttes i  underkant Gjelder Safari)

### ISSUE THREAD

**Issue by Laier68** [navikt/nav-dekoratoren_legacy#667]
Frida ikonet kuttes i  underkant Gjelder Safari)

Liten bug etter deploy av sak #645 
![image](https://user-images.githubusercontent.com/60879532/92871656-71d4b280-f405-11ea-9e43-646c2a720a71.png)

**Comment by ojnybo** [comment]
Denne er rettet
