### ISSUE TITLE
Benytt brødsmulesti og språkvelger fra dekoratøren i våre apper:

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#711]
- [x] XP
- [x] Kontakt oss
- [x] Personopplysninger
- [x] Saksoversikt
- [x] Søknadsveiviser (PR)
- [x] Koronaveiviseren

**Comment by Laier68** [comment]
Jeg har tatt en foreløpige test i Q1 mht det som ligger der per 21/9 kl. 08.45.

**Kontakt oss:** Den ligger jo allerede i prod,, sjekket OK.   (Språk:  Norsk (bokmål) og Engelsk ) 
**Saksoversikt:** Den ligger jo allerede i prod, sjekket OK.   (Språk:  Norsk (bokmål)  Nynorsk og Engelsk)  
**Personopplysninger:** Sjekket i Q1, ser at brødsmulestien viser **...** istedenfor Ditt NAV.    (Språk: kun Norsk (bokmål) pt) 
Har dette noe med lange brødsmulestier å gjøre jfr mitt generelle pkt i bunn. 
![image](https://user-images.githubusercontent.com/60879532/93739815-73faf600-fbe9-11ea-9a42-0c2063342235.png)
 **Søknadsveiviser:** :  Sjekket i Q1, sjekket OK (Språk:  Norsk (bokmål) og Engelsk ) 



Generelt
1)  Det  er jo potensiale for at brødsmulestiene blir lange som igjen medfører at det visuelt blir "mye" brødsmulesti i mobil visning i tillegg kommer en evt. språkvelger også. (På XP sider vil jo dette kunne lange greier) Mulig dere har en plan mtp dette. Det er jo også ganske mye space mellom de ulike elementene i brødsmulestien! (Bør det komprimeres noe?)
Eks: 
![image](https://user-images.githubusercontent.com/60879532/93740004-ecfa4d80-fbe9-11ea-8923-6232c389961e.png)

Sjekkpkt:
- Opprettholde valgt språk mellom apper.
- Opprettholde valgt språk ved refresh.
- Sjekk at lenker i brødsmulestien(e) fungerer.
- Sjekk av brødsmulesti/språkvelger i noen browsere (chrome, IE11, Firefox, Edge) fra laptop.
