### ISSUE TITLE
Dekoratøren: Visning av fnr når PDL er nede/ikke svarer

### ISSUE THREAD

**Issue by Laier68** [navikt/nav-dekoratoren_legacy#792]
Dekoratøren benytter endepunktet "Innloggingsstatus" for å vises navn på innlogget bruker. (Innloggingsstatus henter på sin side navn fra PDL) 
![image](https://user-images.githubusercontent.com/60879532/98814553-200cd080-2426-11eb-8f13-0884d5551624.png)

I tilfellene hvor PDL er er nede/ikke svarer returnerer endepunktet "Innloggingsstatus" innlogget brukeres 
fnr, dette vil da vises slik i dekoratøren.
![image](https://user-images.githubusercontent.com/60879532/98815078-e7b9c200-2426-11eb-9f57-e3e21044d282.png)

Spørsmålet er om dette er ok eller om man skulle presentert det på en annen måte? 

NB: Per i dag i prod vises brukers fnr i de tilfellene man ikke får hentet navn (slik har det vært lenge) m

**Comment by theasteen** [comment]
Hvis kallet etter brukers navn feiler, vises fødselsnummer. Er det noe risiko knyttet til det?

**Comment by ojnybo** [comment]
Backlog grooming 1204. Formattere fnr. og Vise Fnr: foran ved manglende respons fra backend

**Comment by Laier68** [comment]
Vi kjører dialogen rundt test av saken i slack tråd:
https://nav-it.slack.com/archives/C01URBQ5CV9/p1619423905025000

**Comment by Laier68** [comment]
Testing utført i dev.
Endringen er kun en formattering av fnr 
Vises slik:  xxxxxx xxxxx istedenfor slik: xxxxxxxxxxx

Testet med å logge inn med skarp bruker i dev, finnes ikke skarpe brukere i PDL og antas derfor at det er "realistisk test" 

Før
![image](https://user-images.githubusercontent.com/60879532/116238135-4b2f7600-a761-11eb-89aa-433caceaedd0.png)

Etter
![image](https://user-images.githubusercontent.com/60879532/116238117-466ac200-a761-11eb-8e87-12ebe0361858.png)

Foretok en ordinær innlogging med bruker som ligger i PDL
Alt OK i visning av navn dvs som før

![image](https://user-images.githubusercontent.com/60879532/116238936-559e3f80-a762-11eb-858c-fa27cc937e26.png)
