### ISSUE TITLE
Lag en modul for å hente dekoratøren server-side

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#796]
Samtlige team lager en egen variant for å hente dekoratøren server-side.
Dette kan muligens være en modul i en pakke for enklere implementasjon

Eks:
```
import {fetchDekoratørData} from '@navikt/nav-dekoratoren-moduler';
const {HEADER, STYLES, FOOTER, SCRIPTS} = await fetchDekoratørData({brødsmuler: [...], context: 'Privat', cache: 3600, {...etc}});
```

**Comment by theasteen** [comment]
Forslag fra teamene om at de ønsker seg denne funksjonaliteten for å gjøre det enklere å ta den i bruk med server-side rendering
