### ISSUE TITLE
UU - 2.4.4: Sørge for at lenker i hovedmenyen får unike aria-labels for å unngå like lenketekster med innhold i aktuell side.

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-dekoratoren_legacy#825]

**Comment by mjansrud** [comment]
La inn et spørsmål til UU-gjengen: https://nav-it.slack.com/archives/C7MANSGLS/p1609849469062100

**Comment by PerOlavM** [comment]
Enighet om at dette er en IKKE-sak.  Skjermleser vil fortelle kontekst (navigasjon, hvovedmeny), da er det bare en ulempe for bruker at dette blir gjentatt for hvert element i menyen.
