### ISSUE TITLE
UU: Språk mangler i html-tag. Språk har blitt borte fra Dekoratøren?

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-dekoratoren_legacy#851]

**Comment by tomanders** [comment]
https://github.com/navikt/nav-enonicxp-frontend/pull/208

**Comment by tomanders** [comment]
Virker som om dekoratøren ikke får satt språk dynamisk hvis property mangler i det store og hele. Så har funnet en metode for å få satt dette i appen.
