### ISSUE TITLE
UU: Sett tittel på iframe for Google Analytics

### ISSUE THREAD

**Issue by PerOlavM** [navikt/nav-dekoratoren_legacy#852]

**Comment by idaons** [comment]
Iframen kommer fra https://www.npmjs.com/package/react-gtm-module, men jeg laget en pr til repoet der jeg la til tittel, så får vi se. Tror ikke det egentlig er nødvendig siden iframen har "display:none" satt, men greit å slippe å få warningen fra siteimprove.
