### ISSUE TITLE
Endre tekstinnhold på knapp på mobiltastatur ved «aktivt søk inputfelt»

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#860]
Knapp på mobiltastatur blir til Søk når fokus flyttes til inputfelt. (Hadde vært veldig tøft med ikon, men er det mulig å få til?)
Endre tekst info på knapp fra «return» til «Search» (Søk)

**Comment by Laier68** [comment]
**Tatt en første test via i browserstack** 
Iphone 12  IOS 14
![image](https://user-images.githubusercontent.com/60879532/104086151-9a56a700-5255-11eb-8c82-3212cdeddbb2.png)
Samsung Galaxy S20 Android 10
![image](https://user-images.githubusercontent.com/60879532/104086303-fec63600-5256-11eb-9847-0282fab5255c.png)
Det å utføre selve søke fungerer på samme måte som om man trykker på "søke ikonet" i selve appen mao alt OK.  

Kult !  @chrisarnesen

**Comment by Laier68** [comment]
Testet litt mer i saken.

1) Mobil
IOS: Endringen støttes fra ver 12 og høyere. (Ver 11 og lavere vises return knapp dvs som idag)
Android: Ser at søkeikonet støttes i ver 4 og høyere. (Siste Android versjon er pt 10)

2) Nettbrett
Jeg ser at det på en Ipad med IOS 14 som ikke benytter mobil visning, vil det vises standard returnknapp, for et Android nettbrett som benytter mobil visning vil det vises søkeikon.

iPad Pro 12.9 2020  (IOS 14)
![image](https://user-images.githubusercontent.com/60879532/104151688-f51b0a80-53dd-11eb-9c5d-c61c760f1e81.png)

Samsung Galaxy Tab S7 (Android 10)
![image](https://user-images.githubusercontent.com/60879532/104151733-0a903480-53de-11eb-8af5-71c0802b2cb0.png)

**Comment by Laier68** [comment]
Saken er ferdig testet !
