### ISSUE TITLE
Forbedre ytelsen til dekoratøren + oppdatere avhengigheter

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#868]

**Comment by Laier68** [comment]
Jeg skal påbegynne en form for en 1) regresjonstest a) Uinnlogget b) Innlogget samt ta en runde i 2) ulike plattformer/device`r via browserstack

Mission fra Morten J.
![image](https://user-images.githubusercontent.com/60879532/103983215-2b118200-5185-11eb-9cbd-09c090521505.png)

**Comment by Laier68** [comment]
1) Enkel regresjonstest 
a) Dekoratøren i uinnlogget tilstand (n3 og n4)

Sjekket header/footer funksjonalitet og visning. (med utg.pkt i chrome 87.0.4280.141)

- [x] Det ser ut til å fungere og oppleves som uendret ved en direkte sjekk mot produksjon.
       Header: Hamburgermeny, Søk, horisontal toppmeny, Logg inn knapp (pluss brødsmulesti, språkvelger, varslingsfelt) 
![image](https://user-images.githubusercontent.com/60879532/103985699-b4c34e80-5189-11eb-990b-6af7c047f7d9.png)
       Footer: Lenker, Del skjerm
![image](https://user-images.githubusercontent.com/60879532/103985755-d290b380-5189-11eb-9632-de96c6574ab6.png)

b) Dekoratøren i innlogget tilstand

Sjekket header/footer funksjonalitet og visning. (med utg.pkt i chrome 87.0.4280.141)

- [x] Det ser ut til å fungere og oppleves som uendret ved en direkte sjekk mot produksjon.
       Header: Hamburgermeny, Søk, horisontal toppmeny, Ditt NAV meny. Logg inn knapp (pluss brødsmulesti, språkvelger, varslingsfelt) 
![image](https://user-images.githubusercontent.com/60879532/103986386-ef79b680-518a-11eb-8891-696dcbd00cf1.png)
    Footer: Lenker, Del skjerm pluss samspill Privatperson, Arbeidsgiver, Samarbeidspartner og header.
![image](https://user-images.githubusercontent.com/60879532/103986448-06b8a400-518b-11eb-9597-54f7e31b5874.png)
         
2) Stikprøver i ulike plattformer/device`r via browserstack

**Mobil**
- [x] IOS 14 - Iphone  / Safari 14 og chrome
- [x] IOS 13 - Iphone  / Safari 13
- [x] IOS 12 - Iphone 8  / Safari 12
- [x] Android 10 - Samsung S20 / Chrome / Firefox
- [x] Android 9 - Samsung S10 / Chrome (kun uinnlogget sjekk)
- [x] Android 8 - Samsung 9 / Chrome  (kun uinnlogget sjekk)
**Nettbrett**
- [x] Android 10 - Samsung Galaxy Tab S7
- [x] IOS 14 - IPad Pro 12.9 2020
**Mac** 
- [x] OS Big Sur / Safari 14
- [x] OS Catilina / Safari 13 (kun uinnlogget sjekk)

**Comment by Laier68** [comment]
Anser denne saken som ferdig testet. Observert et avvik det er at varselbjella ikke viste siste meldinger lengre. Dette skal etter sigende være relatert til namespaceendringer for varselinnboks. Følgende sak fra Jørn N. L. ligger klar https://github.com/navikt/nav-dekoratoren/pull/871 
Da er #871 sjekket OK i Q1.

**Comment by Laier68** [comment]
Klar for produksjonssetting sett fra et testmessig ståsted.

**Comment by Laier68** [comment]
Her viste det seg etter prod.setting at det ble problemer i eldre Edge versjoner (Edge ver 44 benyttes på publikums pc`er).
Fra et testståsted gikk det definitivt under radaren, endringene ble derimot testet OK i Edge ver 87. (Chrome, Vivaldi, Opera, Firefox + et sett med ulike enheter/pattformer ref. tidligere kommentar i saken) 
At det var problemer kunne jeg nok oppdaget hvis jeg hadde tatt en sjekk i IE11 (som i og for seg NAV ikke støtter lengre) der var de samme symptomene som for Edge ver 44, men det ble altså ikke gjort.                                                             
Testmessig konklusjon:  I NAV man vi faktisk også sjekke at endringer (i våre løsninger) fungerer i Edge ver 44 . Det dreier seg selvfølgelig om saker hvor visning/oppførsel antas å kunne være forskjellig i ulike browsere.
