### ISSUE TITLE
Nytt ikon for ny situasjon “Har du mistet noen i nær familie”

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#903]
Har vi et ikon som vi kan bruke på den nye situasjonen “Har du mistet noen i nær familie”? Eller må nytt ikon utarbeidet.

Bør ikke være religiøst, dvs. en due, blomst eller noe annet?

**Comment by tobiasmcvey** [comment]
Dette repoet har lenker til mange systemer med gratis open source ikoner
https://github.com/meronex/meronex-icons

Den første har flere blomsterikoner vi kan bruke 
https://fontawesome.com/icons?d=gallery&q=flower

**Comment by ghost** [comment]
Takk for lenker @tobiasmcvey

**Comment by ghost** [comment]
Nytt ikon er tegnet opp og sendt til publisering.

Ny situasjonen “Har du mistet noen i nær familie”?
Hva beskriver denne situasjonen best?
Blomst, rose, stearinlys
Bør ikke være religiøst. Ikke gravstøtte, kors, kiste, engel, due.

Når vi begynner å jobbe med livssituasjoner, bør vi brukerteste ulike ikoner pr situasjon.
