### ISSUE TITLE
Finne løsning for å tilby fritekstsvarene på fant-du-det-du-lette-etter til teamene 

### ISSUE THREAD

**Issue by mjansrud** [navikt/nav-dekoratoren_legacy#906]
Ref. https://nav-it.slack.com/archives/CAFRFDJMN/p1610364502167500?thread_ts=1610362180.163900&cid=CAFRFDJMN

**Comment by tobiasmcvey** [comment]
Tilgang til databasen får man via Dataplattformen. Når man har tilgang så kan man lese fra den til sin applikasjon. Dokumentert her:

https://dataplattform.gitbook.io/nada/analyseplattform/bigquery/dekoratoren

**Comment by tobiasmcvey** [comment]
Her er repo for å hente data med Python og laste ned svar til Excel-filer
https://github.com/navikt/pb-notebook

Både designere og utviklere etterspør en enklere form for GUI for å søke i fritekstsvar og laste ned som Excel

Jeg tror Shiny-apper med R kan løse oppgaven, så setter av litt tid for å se på hvordan en kan settes opp i Docker og kjøre som en webapp.

Eksempler for GUI der man kan søke i tabeller og på innhold i datasettene
https://shiny.rstudio.com/gallery/datatables-demo.html

Eksempler på GUI der man kan laste ned filer som vedlegg, f.eks til Excel 
https://shiny.rstudio.com/gallery/file-download.html

**Comment by tobiasmcvey** [comment]
Shiny kan brukes for å lage en webapp men hvis vi ønsker autentisering over SSO så trenger vi kanskje noe som Shinyproxy også. Den støtter flere typer Single Sign on som SAML2, OIDC, kerberos og flere.

https://www.shinyproxy.io/documentation/configuration/

**Comment by tobiasmcvey** [comment]
Vi har lagt ut svarene her
https://data.adeo.no/datapakke/8ae5e4b96db1a1d0d5c9dbc95cd27a44
