### ISSUE TITLE
Telefonnummer side

### ISSUE THREAD

**Issue by ghost** [navikt/nav-dekoratoren_legacy#964]
Hvordan kan vi forbedre innhold/struktur og det visuelle her.

https://www.nav.no/no/nav-og-samfunn/kontakt-nav/kontakt-nav-pa-telefon2

**Comment by Olavrusten** [comment]
Ja, det er litt forskjellig å tenke på når det gjelder endring av denne siden, og vi bør vel også ha dialog med NKS rundt skisser. Tekstgrep kan absolutt være aktuelt, så kommer også  livssituasjonsarbeidet der man planlegger kobling mellom situasjonene og spesialnumre, og om det bør få noen konsekvenser for hvordan vi utformer siden(?) Så er det også sidens knytning til selve kontakt-oss-siden. Tobias har dokumentert at mange kommer rett til telefonsiden fra søkemotorer, og mister informasjon om de skriftlige kanalene våre. Derfor burde nok telefonsiden vært integrert på kontakt-oss-siden på en bedre måte. Dette diskuterte vi da vi lagde kontakt-oss-siden, som du sikkert husker, men landet den gangen på en egen side for telefonnumrene. Så er det også et spørsmål om telefonsiden skal ligge i Enonic (som nå), eller i Sanity (som kontakt-oss-siden). Det har kanskje ikke betydning for designet, men kan ha betydning ift. hvor tett vi klarer å integrere telefonnummersiden med kontakt-oss-siden. Det har også betydning for hvor enkelt det blir å vedlikeholde innhold på telefonnummersiden.
